/**
 * What this platform can actually detect, and what it deliberately does not claim to.
 *
 * ── The screen this replaced ──────────────────────────────────────────────────
 * "Surveillance" listed wash trading, spoofing, layering, ramping and cross-account
 * collusion, each with a confidence percentage, a notional in dollars and a named
 * account. Every one of those patterns is defined over *order* events — resting
 * orders, cancellations, the shape of a book as it moves. This platform has no
 * matching engine, no order table and no trade table. There was nothing to detect
 * them from, and there was no model: the percentages were fixtures.
 *
 * An invented confidence score attached to a real customer's handle is an
 * accusation of market abuse generated by nothing. It is the most dangerous single
 * artefact in a compliance console, because it is the one somebody escalates.
 *
 * ── What replaced it ──────────────────────────────────────────────────────────
 * Rules over movements this platform genuinely records. Each one is a statement
 * about stored rows that an operator can check by opening the rows, and each is
 * reported with the evidence that triggered it rather than a score. There is no
 * confidence field at all — a deterministic rule either matched or it did not, and
 * dressing that as 97% would be inventing precision a second time.
 *
 * ── Why the thresholds live here and the queries do not ───────────────────────
 * Set-based detection has to run in the database; counting every withdrawal in the
 * application to find three in a day is not a design. So the *evaluation* is SQL in
 * the infrastructure adapter, and the numbers that define each rule are here, in
 * one reviewable list. Changing what counts as suspicious is a diff in this file.
 */

export type RiskRule =
  | 'shared-destination'
  | 'credit-mismatch'
  | 'withdrawal-velocity'
  | 'repeated-refusals'
  | 'retry-after-refusal';

/** Which signals deserve the eye first. Derived from the rule, never stored. */
export type RiskSeverity = 'high' | 'medium' | 'low';

export interface RiskRuleDefinition {
  readonly rule: RiskRule;
  readonly title: string;
  /** What the rule looks for, in a sentence an operator reads once. */
  readonly description: string;
  /** Why it is worth a person's time — the reason it is not simply noise. */
  readonly rationale: string;
  readonly severity: RiskSeverity;
}

/**
 * How many withdrawal requests in a day is worth looking at.
 *
 * Three rather than two: two is an ordinary correction after a typo'd address, and
 * a rule that fires on ordinary behaviour is one operators learn to dismiss without
 * reading — which is how the real one gets dismissed too.
 */
export const VELOCITY_THRESHOLD = 3;
export const VELOCITY_WINDOW_HOURS = 24;

/** How long after a refusal a fresh request still reads as a retry. */
export const RETRY_WINDOW_HOURS = 1;

/** How many refused deposit claims before the pattern is the point. */
export const REFUSAL_THRESHOLD = 2;

export const RISK_RULES: Readonly<Record<RiskRule, RiskRuleDefinition>> = {
  'shared-destination': {
    rule: 'shared-destination',
    title: 'One address, several accounts',
    description:
      'The same withdrawal destination has been used by more than one account.',
    rationale:
      'The clearest signal this platform can produce from its own data. Separate accounts paying out to one address are either the same person holding several, or one person collecting from accounts they control — and both matter before the next payout leaves.',
    severity: 'high',
  },
  'retry-after-refusal': {
    rule: 'retry-after-refusal',
    title: 'Requested again straight after a refusal',
    description: `A withdrawal was requested within ${RETRY_WINDOW_HOURS} hour of one being rejected.`,
    rationale:
      'Usually somebody fixing a mistake, and worth seeing anyway: the same pattern is what probing looks like, and the two are told apart by reading the rejection reason beside the new request.',
    severity: 'high',
  },
  'credit-mismatch': {
    rule: 'credit-mismatch',
    title: 'Credited a different amount than claimed',
    description:
      'An approved deposit was credited at an amount that differs from the one the customer reported.',
    rationale:
      'Ordinary — network fees and partial sends do this — and it is also what an operator crediting the wrong figure looks like. The claim and the credit are both kept precisely so this comparison can be made.',
    severity: 'medium',
  },
  'withdrawal-velocity': {
    rule: 'withdrawal-velocity',
    title: 'Several withdrawals in a day',
    description: `${VELOCITY_THRESHOLD} or more withdrawal requests from one account within ${VELOCITY_WINDOW_HOURS} hours.`,
    rationale:
      'Draining an account in instalments is what a compromised session does, because each request alone stays under whatever limit it found.',
    severity: 'medium',
  },
  'repeated-refusals': {
    rule: 'repeated-refusals',
    title: 'Repeatedly refused deposits',
    description: `${REFUSAL_THRESHOLD} or more deposit claims from one account have been rejected.`,
    rationale:
      'Either somebody who cannot get the evidence right and needs help, or somebody testing what an operator will accept. Both are worth a look; only one is a support problem.',
    severity: 'low',
  },
};

/** Ordering for the console: worst first, then newest within a severity. */
export const SEVERITY_ORDER: Readonly<Record<RiskSeverity, number>> = {
  high: 0,
  medium: 1,
  low: 2,
};
