import type { Metadata } from 'next';
import { TriangleAlert } from 'lucide-react';

import { requireAdmin } from '@/server/auth';
import { getRiskConsole } from '@/server/risk';
import { StatTile } from '@/shared/ui/charts/stat-tile';

import { AdminPageHeader, EmptyState } from '../../_components/admin-ui';
import { SignalList } from './_components/signal-list';

/**
 * Surveillance.
 *
 * ── What this page used to claim ──────────────────────────────────────────────
 * Wash trading, spoofing, layering, ramping and cross-account collusion, each with
 * a confidence percentage and a dollar notional, against named accounts. Every one
 * of those patterns is defined over *order* events — resting orders, cancellations,
 * the shape of a book as it moves. This platform has no matching engine, no order
 * table and no trade table, so there was nothing to detect them from. There was no
 * model either: the percentages were fixtures, and "97% confidence" beside a real
 * customer's handle was an accusation of market abuse generated by nothing.
 *
 * ── What it says now ──────────────────────────────────────────────────────────
 * Rules over movements this platform genuinely records — shared payout addresses,
 * deposits credited at a different figure than claimed, withdrawal bursts, retries
 * straight after a refusal, repeatedly refused deposits. Each finding shows the
 * evidence that triggered it, so an operator can check it against the rows rather
 * than trust a number.
 *
 * There is no confidence score anywhere on this page. A deterministic rule either
 * matched or it did not, and dressing that as a percentage would be inventing
 * precision a second time.
 *
 * ── Findings are derived, dispositions are stored ─────────────────────────────
 * Nothing here is an "alert row" written once and left to rot. The rules run against
 * the ledger on every read, so the board cannot describe a world that has moved on.
 * What persists is what an operator decided — see `risk_dispositions`.
 */

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'Surveillance',
  robots: { index: false, follow: false },
};

export default async function SurveillancePage() {
  await requireAdmin('/admin/surveillance');
  const board = await getRiskConsole();

  return (
    <>
      <AdminPageHeader
        title="Surveillance"
        description="Rules over the movements this platform records. Each finding shows the evidence behind it — a rule raises the question, a person answers it."
      />

      {board.unavailable ? (
        <div className="mb-4 flex items-start gap-3 rounded-lg border border-line bg-bg-elev px-4 py-3">
          <TriangleAlert className="mt-0.5 size-4 shrink-0 text-warn" />
          <p className="text-xs leading-relaxed text-fg-muted">
            No ledger is configured on this deployment, so no rules can run.
          </p>
        </div>
      ) : null}

      {board.degraded ? (
        <div className="mb-4 flex items-start gap-3 rounded-lg border border-down/35 bg-down/8 px-4 py-3">
          <TriangleAlert className="mt-0.5 size-4 shrink-0 text-down" />
          <p className="text-xs leading-relaxed text-fg-muted">
            The scan could not run. This is an empty board, not a clean one — do not
            read it as nothing outstanding.
          </p>
        </div>
      ) : null}

      <div className="mb-4 grid gap-4 sm:grid-cols-3">
        <StatTile
          label="Open findings"
          value={String(board.open.length)}
          delta={{ value: 'Worst first', direction: 'flat', period: '' }}
          upIsGood={false}
        />
        <StatTile
          label="Escalated"
          value={String(board.escalated)}
          delta={{ value: 'Marked for a second look', direction: 'flat', period: '' }}
          upIsGood={false}
        />
        <StatTile
          label="Reviewed"
          value={String(board.handled.length)}
          delta={{ value: 'Cleared or escalated', direction: 'flat', period: '' }}
        />
      </div>

      {board.open.length === 0 && board.handled.length === 0 ? (
        <EmptyState
          title={board.degraded ? 'Nothing to show' : 'No findings'}
          body={
            board.degraded
              ? 'The rules could not be evaluated. Try again shortly.'
              : 'Every rule ran and none matched. Findings appear here as deposits and withdrawals accumulate.'
          }
        />
      ) : (
        <SignalList
          open={board.open}
          handled={board.handled}
          accounts={board.accounts}
        />
      )}
    </>
  );
}
